/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vew;

import Connection.Connection_factory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lordt
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {

        initComponents();
        this.setLocationRelativeTo(null);
        //setExtendedState(MAXIMIZED_BOTH);
    }

    public Connection agendamento_DAO() {
        return Connection_factory.getConnetion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_tabelaagendamentos = new javax.swing.JTextArea();
        jB_atualizar = new javax.swing.JButton();
        jB_agendamento = new javax.swing.JButton();
        jB_agendarServico = new javax.swing.JButton();
        jB_cadastrarCliente = new javax.swing.JButton();
        jB_sair = new javax.swing.JButton();
        jB_cadastrarProduto = new javax.swing.JButton();
        jB_cadastrarServico = new javax.swing.JButton();
        jB_verderProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Tela Inicial");

        jT_tabelaagendamentos.setColumns(20);
        jT_tabelaagendamentos.setRows(5);
        jScrollPane1.setViewportView(jT_tabelaagendamentos);

        jB_atualizar.setText("Atualizar");
        jB_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_atualizarActionPerformed(evt);
            }
        });

        jB_agendamento.setText("Agendamento");
        jB_agendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agendamentoActionPerformed(evt);
            }
        });

        jB_agendarServico.setText("Agendar Serviço");
        jB_agendarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agendarServicoActionPerformed(evt);
            }
        });

        jB_cadastrarCliente.setText("Cadastrar Cliente");
        jB_cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastrarClienteActionPerformed(evt);
            }
        });

        jB_sair.setText("Sair");
        jB_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sairActionPerformed(evt);
            }
        });

        jB_cadastrarProduto.setText("Cadastrar Produto");
        jB_cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastrarProdutoActionPerformed(evt);
            }
        });

        jB_cadastrarServico.setText("Cadastrar Serviço");
        jB_cadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastrarServicoActionPerformed(evt);
            }
        });

        jB_verderProduto.setText("Vender Produto");
        jB_verderProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_verderProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_atualizar)
                        .addGap(44, 44, 44)
                        .addComponent(jB_agendamento)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_cadastrarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jB_cadastrarServico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jB_agendarServico)
                    .addComponent(jB_verderProduto))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jB_cadastrarCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jB_sair)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_atualizar)
                    .addComponent(jB_agendamento)
                    .addComponent(jB_agendarServico)
                    .addComponent(jB_cadastrarCliente))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_cadastrarProduto)
                    .addComponent(jB_cadastrarServico)
                    .addComponent(jB_verderProduto)
                    .addComponent(jB_sair))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_atualizarActionPerformed
        String jT_tabelaagendamentos = "";

        try {
            PreparedStatement stmt = (agendamento_DAO()).prepareStatement("Select * From agendamento");
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                //jT_tabelaagendamentos +="..............................................\n";
                jT_tabelaagendamentos += "Código Agendamento: ";
                jT_tabelaagendamentos += rs.getString("cod_agendamento");
                jT_tabelaagendamentos += "\n";
                jT_tabelaagendamentos += "Horario: ";
                jT_tabelaagendamentos += rs.getString("horario");
                jT_tabelaagendamentos += "\n";
                jT_tabelaagendamentos += "Data de Agendamento: ";
                jT_tabelaagendamentos += rs.getString("data_agendamento");
                jT_tabelaagendamentos += "\n";
                jT_tabelaagendamentos += "Cliente: ";
                jT_tabelaagendamentos += rs.getString("cliente");
                jT_tabelaagendamentos += "\n";
                jT_tabelaagendamentos += "Serviço: ";
                jT_tabelaagendamentos += rs.getString("servico");
                jT_tabelaagendamentos += "\n";
                jT_tabelaagendamentos += "..............................................\n";
                this.jT_tabelaagendamentos.setText(jT_tabelaagendamentos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jB_atualizarActionPerformed

    private void jB_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jB_sairActionPerformed

    private void jB_agendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agendamentoActionPerformed
        agendamento obj = new agendamento();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jB_agendamentoActionPerformed

    private void jB_agendarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agendarServicoActionPerformed
        AgendarServiço obj = new AgendarServiço();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_agendarServicoActionPerformed

    private void jB_cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastrarClienteActionPerformed
        CadastrarCliente obj = new CadastrarCliente();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_cadastrarClienteActionPerformed

    private void jB_cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastrarProdutoActionPerformed
        CadastrarProduto obj = new CadastrarProduto();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_cadastrarProdutoActionPerformed

    private void jB_cadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastrarServicoActionPerformed
        CadastrarServico obj = new CadastrarServico();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_cadastrarServicoActionPerformed

    private void jB_verderProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_verderProdutoActionPerformed
        VenderProduto obj = new VenderProduto();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_verderProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_agendamento;
    private javax.swing.JButton jB_agendarServico;
    private javax.swing.JButton jB_atualizar;
    private javax.swing.JButton jB_cadastrarCliente;
    private javax.swing.JButton jB_cadastrarProduto;
    private javax.swing.JButton jB_cadastrarServico;
    private javax.swing.JButton jB_sair;
    private javax.swing.JButton jB_verderProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT_tabelaagendamentos;
    // End of variables declaration//GEN-END:variables
}
